export const gotenborgCities = [
  "göteborg",
  "västra frölunda",
  "askim",
  "angered",
  "hisings backa",
  "hisings kärra",
  "hovås",
  "torslanda",
  "billdal",
  "mölndal",
  "kållered",
  "lindome",
  "partille",
  "sävedalen",
  "jonsered",
  "kundsbacka",
];

export const stockholmCities = [
  "östermalm",
  "järfälla",
  "hägersten",
  "västerhaninge",
  "norrmalm",
  "bromma",
  "sundbyberg",
  "vällingby",
  "huddinge",
  "sollentuna",
  "södermalm",
  "solna",
  "enskede",
  "spånga",
  "lidingö",
  "täby",
  "enebyberg",
  "stocksund",
  "djursholm",
  "danderyd",
  "brandbergen",
  "vendelsö",
  "söderby",
  "norrby",
  "handen",
  "haninge",
  "tullinge",
  "norsborg",
  "saltsjö",
  "nacka",
  "älta",
  "kungsen kurva",
  "trångsund",
  "segeltorp",
  "skogås",
  "vårby",
  "enskede gård",
  "globen",
  "enkeededalen",
  "bagarmossen",
  "sköndal",
  "skarpnäck",
  "årsta",
  "farsta",
  "johanneshov",
  "bandhagen",
  "skärholmen",
  "hässelby",
  "älvsjö",
  "stockholm",
];
