export const synonyms = {
  bostad: {
    omfattande: [
      "omfattande",
      "brett",
      "stort",
      "generöst",
      "heltäckande",
      "rikligt",
      "rigoröst",
    ],
    lediga: ["lediga", "tillgängliga", "vakanta"],
    "tusentals andra sökande": [
      "tusentals andra bostadssökande",
      "många andra bostadsletande",
      "tusentals andra som letar bostad",
      "många andra som letar bostad",
    ],
    "landet över": [
      "landet över",
      "över hela sverige",
      "runt om hela landet",
      "i hela vårt avlånga land",
    ],
    enkelt: ["enkelt", "lätt", "smidigt"],
    chanser: [
      "chanser",
      "möjligheter",
      "sannolikheter",
      "odds",
      "förutsättningar",
    ],
    regelbundet: ["regelbundet", "ofta", "med jämna mellanrum", "frekvent"],
    "en stad med möjligheter": [
      "en stad med möjligheter",
      "en perfekt stad för dig",
      "ett perfekt alternativ för dig",
      "en stad med ett brett utbud av lediga bostäder",
    ],
    partner: [
      "partner",
      "webbplats",
      "sida",
      "bostadssida",
      "hjälp",
      "hjälpreda",
      "vän",
      "källa",
      "resurs",
    ],
    "vårt omfattande": [
      "vårt omfattande",
      "vårt breda",
      "vårt stora",
      "vårt generösa",
      "vårt heltäckande",
      "vårt rikliga",
      "vårt rigorösa",
    ],
    "din drömbostad": [
      "din drömbostad",
      "ditt nästa boende",
      "din nästa bostad,",
    ],
    "användarvänliga webbplats": [
      "användarvänliga webbplats",
      "smarta bostadsportal",
      "stora bostadssida",
      "breda bostadsdatabas",
    ],
    utformad: ["utformad", "skapad", "designad", "gjord"],
    "prisintervall, antal rum, specifika bekvämligheter": [
      "prisintervall, antal rum, specifika bekvämligheter",
      "pris, storlek, antal rum",
      "prisnivå, bekvämligheter, antalet rum ",
    ],
    "sparar din tid": [
      "sparar din tid",
      "är tidseffektivt",
      "snabbar på din bostadssökning",
      "skyndar på ditt bostadsletande",
    ],
    "uppfyller dina önskemål": [
      "uppfyller dina önskemål",
      "lever upp till dina förväntningar",
      "passar dig bäst",
      "är en match för dig",
      "är anpassad för dina krav och önskemål",
    ],
    "en bostad": [
      "en bostad",
      "en eller flera bostäder",
      "vakanta bostäder",
      "en eller flera vakanta bostäder",
      "en ledig bostad",
      "en eller flera lediga bostäder",
    ],
    potentiella: ["potentiella", "blivande", "framtida"],
    "din bostad": [
      "din bostad",
      "dina bostadsannonser",
      "din bostadsannons",
      "dina lediga bostäder",
      "dina lediga bostadsannonser",
      "era tillgängliga bostadsannonser",
      "era lediga bostäder",
    ],
    hitta: ["hitta", "upptäcka"],
    "kontakta dig direkt": [
      "kontakta dig direkt",
      "hyra från er",
      "komma i kontakt med er",
      "hitta era kontaktuppgifter",
    ],
  },
  lagenhet: {
    omfattande: [
      "omfattande",
      "brett",
      "stort",
      "generöst",
      "heltäckande",
      "rikligt",
      "rigoröst",
    ],
    lediga: ["lediga", "tillgängliga", "vakanta"],
    "tusentals andra sökande": [
      "tusentals andra lägenhetssökande",
      "många andra lägenhetsletande",
      "tusentals andra som letar lägenhet",
      "många andra som letar lägenhet",
    ],
    "landet över": [
      "landet över",
      "över hela sverige",
      "runt om hela landet",
      "i hela vårt avlånga land",
    ],
    enkelt: ["enkelt", "lätt", "smidigt"],
    chanser: [
      "chanser",
      "möjligheter",
      "sannolikheter",
      "odds",
      "förutsättningar",
    ],
    regelbundet: ["regelbundet", "ofta", "med jämna mellanrum", "frekvent"],
    "en stad med möjligheter": [
      "en stad med möjligheter",
      "en perfekt stad för dig",
      "ett perfekt alternativ för dig",
      "en stad med ett brett utbud av lediga lägenheter",
    ],
    partner: [
      "partner",
      "webbplats",
      "sida",
      "bostadssida",
      "hjälp",
      "hjälpreda",
      "vän",
      "källa",
      "resurs",
    ],
    "vårt omfattande": [
      "vårt omfattande",
      "vårt breda",
      "vårt stora",
      "vårt generösa",
      "vårt heltäckande",
      "vårt rikliga",
      "vårt rigorösa",
    ],
    "din drömbostad": [
      "din drömbostad",
      "ditt nästa boende",
      "din nästa bostad,",
    ],
    hyreslägenheter: [
      "hyreslägenheter",
      "vakanta lägenheter",
      "lediga lägenheter",
      "tillgängliga lägenheter",
    ],
    drömlägenhet: ["drömlägenhet", "nästa lägenhet"],
    "användarvänliga webbplats": [
      "användarvänliga webbplats",
      "smarta lägenhetsportal",
      "stora lägenhetssida",
      "breda lägenhetsdatabas",
    ],
    utformad: ["utformad", "skapad", "designad", "gjord"],
    "prisintervall, antal rum, specifika bekvämligheter": [
      "prisintervall, antal rum, specifika bekvämligheter",
      "pris, storlek, antal rum",
      "prisnivå, bekvämligheter, antalet rum ",
    ],
    "sparar din tid": [
      "sparar din tid",
      "är tidseffektivt",
      "snabbar på din lägenhetssökning",
      "skyndar på ditt lägenhetsletande",
    ],
    "uppfyller dina önskemål": [
      "uppfyller dina önskemål",
      "lever upp till dina förväntningar",
      "passar dig bäst",
      "är en match för dig",
      "är anpassad för dina krav och önskemål",
    ],
    "en bostad": [
      "en bostad",
      "en eller flera bostäder",
      "vakanta bostäder",
      "en eller flera vakanta bostäder",
      "en ledig bostad",
      "en eller flera lediga bostäder",
    ],
    lägenhet: [
      "en lägenhet",
      "en eller flera lägenheter",
      "vakanta lägenheter",
      "en eller flera vakanta lägenheter",
      "en ledig lägenhet",
      "en eller flera lediga lägenheter",
    ],
    potentiella: ["potentiella", "blivande", "framtida"],
    "din bostad": [
      "din bostad",
      "dina bostadsannonser",
      "din bostadsannons",
      "dina lediga bostäder",
      "dina lediga bostadsannonser",
      "era tillgängliga bostadsannonser",
      "era lediga bostäder",
    ],
    "din lägenhet": [
      "din lägenhet",
      "dina lägenheter",
      "dina lägenhetsannonser",
    ],
    hitta: ["hitta", "upptäcka"],
    "kontakta dig direkt": [
      "kontakta dig direkt",
      "hyra från er",
      "komma i kontakt med er",
      "hitta era kontaktuppgifter",
    ],
  },
  stuga: {
    omfattande: [
      "omfattande",
      "brett",
      "stort",
      "generöst",
      "heltäckande",
      "rikligt",
      "rigoröst",
    ],
    lediga: ["lediga", "tillgängliga", "vakanta"],
    "tusentals andra sökande": [
      "tusentals andra sökande",
      "många andra letande",
      "tusentals andra som letar stuga",
      "många andra som letar stuga",
    ],
    "landet över": [
      "landet över",
      "över hela sverige",
      "runt om hela landet",
      "i hela vårt avlånga land",
    ],
    enkelt: ["enkelt", "lätt", "smidigt"],
    chanser: [
      "chanser",
      "möjligheter",
      "sannolikheter",
      "odds",
      "förutsättningar",
    ],
    regelbundet: ["regelbundet", "ofta", "med jämna mellanrum", "frekvent"],
    "hitta nya": ["hitta nya", "upptäcka nya", "finna nya"],
    "en stad med möjligheter": [
      "en stad med möjligheter",
      "en perfekt stad för dig",
      "ett perfekt alternativ för dig",
      "en stad med ett brett utbud av lediga stugor",
    ],
    partner: [
      "partner",
      "webbplats",
      "sida",
      "bostadssida",
      "hjälp",
      "hjälpreda",
      "vän",
      "källa",
      "resurs",
    ],
    "vårt omfattande": [
      "vårt omfattande",
      "vårt breda",
      "vårt stora",
      "vårt generösa",
      "vårt heltäckande",
      "vårt rikliga",
      "vårt rigorösa",
    ],
    "din drömbostad": [
      "din drömbostad",
      "ditt nästa boende",
      "din nästa bostad,",
    ],
    "användarvänliga webbplats": [
      "användarvänliga webbplats",
      "smarta bostadsportal",
      "stora bostadssida",
      "breda bostadsdatabas",
    ],
    utformad: ["utformad", "skapad", "designad", "gjord"],
    "prisintervall, antal rum, specifika bekvämligheter": [
      "prisintervall, antal rum, specifika bekvämligheter",
      "pris, storlek, antal rum",
      "prisnivå, bekvämligheter, antalet rum ",
    ],
    "sparar din tid": [
      "sparar din tid",
      "är tidseffektivt",
      "snabbar på din stugsökning",
      "skyndar på ditt stugletande",
    ],
    "uppfyller dina önskemål": [
      "uppfyller dina önskemål",
      "lever upp till dina förväntningar",
      "passar dig bäst",
      "är en match för dig",
      "är anpassad för dina krav och önskemål",
    ],
    "en bostad": [
      "en bostad",
      "en eller flera bostäder",
      "vakanta bostäder",
      "en eller flera vakanta bostäder",
      "en ledig bostad",
      "en eller flera lediga bostäder",
    ],
    potentiella: ["potentiella", "blivande", "framtida"],
    "din bostad": [
      "din bostad",
      "dina bostadsannonser",
      "din bostadsannons",
      "dina lediga bostäder",
      "dina lediga bostadsannonser",
      "era tillgängliga bostadsannonser",
      "era lediga bostäder",
    ],
    hitta: ["hitta", "upptäcka"],
    "kontakta dig direkt": [
      "kontakta dig direkt",
      "hyra från er",
      "komma i kontakt med er",
      "hitta era kontaktuppgifter",
    ],
  },
  rum: {
    omfattande: [
      "omfattande",
      "brett",
      "stort",
      "generöst",
      "heltäckande",
      "rikligt",
      "rigoröst",
    ],
    lediga: ["lediga", "tillgängliga", "vakanta"],
    "tusentals andra sökande": [
      "tusentals andra sökande",
      "många andra letande",
      "tusentals andra som letar rum",
      "många andra som letar rum",
    ],
    "landet över": [
      "landet över",
      "över hela sverige",
      "runt om hela landet",
      "i hela vårt avlånga land",
    ],
    enkelt: ["enkelt", "lätt", "smidigt"],
    chanser: [
      "chanser",
      "möjligheter",
      "sannolikheter",
      "odds",
      "förutsättningar",
    ],
    regelbundet: ["regelbundet", "ofta", "med jämna mellanrum", "frekvent"],
    "hitta nya": ["hitta nya", "upptäcka nya", "finna nya"],
    "en stad med möjligheter": [
      "en stad med möjligheter",
      "en perfekt stad för dig",
      "ett perfekt alternativ för dig",
      "en stad med ett brett utbud av lediga stugor",
    ],
    partner: [
      "partner",
      "webbplats",
      "sida",
      "bostadssida",
      "hjälp",
      "hjälpreda",
      "vän",
      "källa",
      "resurs",
    ],
    "vårt omfattande": [
      "vårt omfattande",
      "vårt breda",
      "vårt stora",
      "vårt generösa",
      "vårt heltäckande",
      "vårt rikliga",
      "vårt rigorösa",
    ],
    "din drömbostad": [
      "din drömbostad",
      "ditt nästa boende",
      "din nästa bostad,",
    ],
    "användarvänliga webbplats": [
      "användarvänliga webbplats",
      "smarta bostadsportal",
      "stora bostadssida",
      "breda bostadsdatabas",
    ],
    utformad: ["utformad", "skapad", "designad", "gjord"],
    "prisintervall, antal rum, specifika bekvämligheter": [
      "prisintervall, antal rum, specifika bekvämligheter",
      "pris, storlek, antal rum",
      "prisnivå, bekvämligheter, antalet rum ",
    ],
    "sparar din tid": [
      "sparar din tid",
      "är tidseffektivt",
      "snabbar på din stugsökning",
      "skyndar på ditt stugletande",
    ],
    "uppfyller dina önskemål": [
      "uppfyller dina önskemål",
      "lever upp till dina förväntningar",
      "passar dig bäst",
      "är en match för dig",
      "är anpassad för dina krav och önskemål",
    ],
    "en bostad": [
      "en bostad",
      "en eller flera bostäder",
      "vakanta bostäder",
      "en eller flera vakanta bostäder",
      "en ledig bostad",
      "en eller flera lediga bostäder",
    ],
    potentiella: ["potentiella", "blivande", "framtida"],
    "din bostad": [
      "din bostad",
      "dina bostadsannonser",
      "din bostadsannons",
      "dina lediga bostäder",
      "dina lediga bostadsannonser",
      "era tillgängliga bostadsannonser",
      "era lediga bostäder",
    ],
    hitta: ["hitta", "upptäcka"],
    "kontakta dig direkt": [
      "kontakta dig direkt",
      "hyra från er",
      "komma i kontakt med er",
      "hitta era kontaktuppgifter",
    ],
  },
  hus: {
    omfattande: [
      "omfattande",
      "brett",
      "stort",
      "generöst",
      "heltäckande",
      "rikligt",
      "rigoröst",
    ],
    lediga: ["lediga", "tillgängliga", "vakanta"],
    "tusentals andra sökande": [
      "tusentals andra sökande",
      "många andra letande",
      "tusentals andra som letar hus",
      "många andra som letar hus",
    ],
    "tusentals andra lägenhetssökande": [
      "tusentals andra lägenhetssökande",
      "många andra lägenhetsletande",
      "tusentals andra som letar lägenhet",
      "många andra som letar lägenhet",
    ],
    "landet över": [
      "landet över",
      "över hela sverige",
      "runt om hela landet",
      "i hela vårt avlånga land",
    ],
    enkelt: ["enkelt", "lätt", "smidigt"],
    chanser: [
      "chanser",
      "möjligheter",
      "sannolikheter",
      "odds",
      "förutsättningar",
    ],
    regelbundet: ["regelbundet", "ofta", "med jämna mellanrum", "frekvent"],
    "en stad med möjligheter": [
      "en stad med möjligheter",
      "en perfekt stad för dig",
      "ett perfekt alternativ för dig",
      "en stad med ett brett utbud av lediga lägenheter",
    ],
    partner: [
      "partner",
      "webbplats",
      "sida",
      "bostadssida",
      "hjälp",
      "hjälpreda",
      "vän",
      "källa",
      "resurs",
    ],
    "vårt omfattande": [
      "vårt omfattande",
      "vårt breda",
      "vårt stora",
      "vårt generösa",
      "vårt heltäckande",
      "vårt rikliga",
      "vårt rigorösa",
    ],
    "din drömbostad": [
      "din drömbostad",
      "ditt nästa boende",
      "din nästa bostad,",
    ],
    "användarvänliga webbplats": [
      "användarvänliga webbplats",
      "smarta bostadsportal",
      "stora bostadsportal",
      "breda bostadsportal",
    ],
    utformad: ["utformad", "skapad", "designad", "gjord"],
    "prisintervall, antal rum, specifika bekvämligheter": [
      "prisintervall, antal rum, specifika bekvämligheter",
      "pris, storlek, antal rum",
      "prisnivå, bekvämligheter, antalet rum",
    ],
    "sparar din tid": [
      "sparar din tid",
      "är tidseffektivt",
      "snabbar på din lägenhetssökning",
      "skyndar på ditt lägenhetsletande",
    ],
    "uppfyller dina önskemål": [
      "uppfyller dina önskemål",
      "lever upp till dina förväntningar",
      "passar dig bäst",
      "är en match för dig",
      "är anpassad för dina krav och önskemål",
    ],
    "en bostad": [
      "en bostad",
      "en eller flera bostäder",
      "vakanta bostäder",
      "en eller flera vakanta bostäder",
      "en ledig bostad",
      "en eller flera lediga bostäder",
    ],
    potentiella: ["potentiella", "blivande", "framtida"],
    "din bostad": [
      "din bostad",
      "dina bostadsannonser",
      "din bostadsannons",
      "dina lediga bostäder",
      "dina lediga bostadsannonser",
      "era tillgängliga bostadsannonser",
      "era lediga bostäder",
    ],
    hitta: ["hitta", "upptäcka"],
    "kontakta dig direkt": [
      "kontakta dig direkt",
      "hyra från er",
      "komma i kontakt med er",
      "hitta era kontaktuppgifter",
    ],
  },
} as const;
